### ISSUE TITLE
system_monitor script doesn't provide help text

### ISSUE THREAD

**Issue by lukechurch** [larksystems/nook#288]
```
lukes-mbp:tool lukechurch$ pipenv run python system_metrics_monitor.py 
Traceback (most recent call last):
  File "system_metrics_monitor.py", line 83, in <module>
    run_system_metric_monitor()
  File "system_metrics_monitor.py", line 78, in run_system_metric_monitor
    initialize_firebase(sys.argv[1])
IndexError: list index out of range
```

@ktkization  Please could you fix so that if called without argument it provides help text explaining how it should be run?

**Comment by ktkization** [comment]
@marianamarasoiu assign this to me please

**Comment by ktkization** [comment]
Here's the [PL](https://github.com/larksystems/nook/pull/292)
